md icon1
copy 备忘录\1.png /y icon1\com.example.android.notepad.png
copy 电话\1.png /y icon1\com.android.contacts.activities.DialtactsActivity.png
copy 短信\1.png /y icon1\com.android.mms.png
copy 服务\1.png /y icon1\com.huawei.phoneservice.png
copy 华为阅读1\1.png /y icon1\com.huawei.hwireader.png
copy 华为阅读2\1.png /y icon1\com.huawei.hwread.al.png
copy 联系人\1.png /y icon1\com.android.contacts.png
copy 钱包\1.png /y icon1\com.huawei.wallet.png
copy 日历\1.png /y icon1\com.android.calendar.png
copy 荣耀阅读\1.png /y icon1\com.huawei.hnreader.png
copy 设置\1.png /y icon1\com.android.settings.png
copy 生活服务\1.png /y icon1\com.huawei.lives.png
copy 时钟\1.png /y icon1\com.android.deskclock.png
copy 手机管家\1.png /y icon1\com.huawei.systemmanager.png
copy 图库\1.png /y icon1\com.android.gallery3d.png
copy 相机\1.png /y icon1\com.huawei.camera.png
copy 音乐\1.png /y icon1\com.android.mediacenter.png
copy 应用市场\1.png /y icon1\com.huawei.appmarket.png
copy 邮件\1.png /y icon1\com.android.email.png
copy 浏览器\1.png /y icon1\com.android.browser.png
copy 浏览器2\1.png /y icon1\com.huawei.browser.png
copy 游戏中心1\1.png /y icon1\com.huawei.gamebox.globald.png
copy 游戏中心2\1.png /y icon1\com.huawei.gamebox.png
copy 游戏中心3\1.png /y icon1\com.huawei.gamecenter.png
copy 运动健康\1.png /y icon1\com.huawei.health.png
copy 主题\1.png /y icon1\com.huawei.android.thememanager.png

md icon2
copy 备忘录\2.png /y icon2\com.example.android.notepad.png
copy 电话\2.png /y icon2\com.android.contacts.activities.DialtactsActivity.png
copy 短信\2.png /y icon2\com.android.mms.png
copy 服务\2.png /y icon2\com.huawei.phoneservice.png
copy 华为阅读1\2.png /y icon2\com.huawei.hwireader.png
copy 华为阅读2\2.png /y icon2\com.huawei.hwread.al.png
copy 联系人\2.png /y icon2\com.android.contacts.png
copy 钱包\2.png /y icon2\com.huawei.wallet.png
copy 日历\2.png /y icon2\com.android.calendar.png
copy 荣耀阅读\2.png /y icon2\com.huawei.hnreader.png
copy 设置\2.png /y icon2\com.android.settings.png
copy 生活服务\2.png /y icon2\com.huawei.lives.png
copy 时钟\2.png /y icon2\com.android.deskclock.png
copy 手机管家\2.png /y icon2\com.huawei.systemmanager.png
copy 图库\2.png /y icon2\com.android.gallery3d.png
copy 相机\2.png /y icon2\com.huawei.camera.png
copy 音乐\2.png /y icon2\com.android.mediacenter.png
copy 应用市场\2.png /y icon2\com.huawei.appmarket.png
copy 邮件\2.png /y icon2\com.android.email.png
copy 浏览器\2.png /y icon2\com.android.browser.png
copy 浏览器2\2.png /y icon2\com.huawei.browser.png
copy 游戏中心1\2.png /y icon2\com.huawei.gamebox.globald.png
copy 游戏中心2\2.png /y icon2\com.huawei.gamebox.png
copy 游戏中心3\2.png /y icon2\com.huawei.gamecenter.png
copy 运动健康\2.png /y icon2\com.huawei.health.png
copy 主题\2.png /y icon2\com.huawei.android.thememanager.png

md icon3
copy 备忘录\3.png /y icon3\com.example.android.notepad.png
copy 电话\3.png /y icon3\com.android.contacts.activities.DialtactsActivity.png
copy 短信\3.png /y icon3\com.android.mms.png
copy 服务\3.png /y icon3\com.huawei.phoneservice.png
copy 华为阅读1\3.png /y icon3\com.huawei.hwireader.png
copy 华为阅读2\3.png /y icon3\com.huawei.hwread.al.png
copy 联系人\3.png /y icon3\com.android.contacts.png
copy 钱包\3.png /y icon3\com.huawei.wallet.png
copy 日历\3.png /y icon3\com.android.calendar.png
copy 荣耀阅读\3.png /y icon3\com.huawei.hnreader.png
copy 设置\3.png /y icon3\com.android.settings.png
copy 生活服务\3.png /y icon3\com.huawei.lives.png
copy 时钟\3.png /y icon3\com.android.deskclock.png
copy 手机管家\3.png /y icon3\com.huawei.systemmanager.png
copy 图库\3.png /y icon3\com.android.gallery3d.png
copy 相机\3.png /y icon3\com.huawei.camera.png
copy 音乐\3.png /y icon3\com.android.mediacenter.png
copy 应用市场\3.png /y icon3\com.huawei.appmarket.png
copy 邮件\3.png /y icon3\com.android.email.png
copy 浏览器\3.png /y icon3\com.android.browser.png
copy 浏览器2\3.png /y icon3\com.huawei.browser.png
copy 游戏中心1\3.png /y icon3\com.huawei.gamebox.globald.png
copy 游戏中心2\3.png /y icon3\com.huawei.gamebox.png
copy 游戏中心3\3.png /y icon3\com.huawei.gamecenter.png
copy 运动健康\3.png /y icon3\com.huawei.health.png
copy 主题\3.png /y icon3\com.huawei.android.thememanager.png

md icon4
copy 备忘录\4.png /y icon4\com.example.android.notepad.png
copy 电话\4.png /y icon4\com.android.contacts.activities.DialtactsActivity.png
copy 短信\4.png /y icon4\com.android.mms.png
copy 服务\4.png /y icon4\com.huawei.phoneservice.png
copy 华为阅读1\4.png /y icon4\com.huawei.hwireader.png
copy 华为阅读2\4.png /y icon4\com.huawei.hwread.al.png
copy 联系人\4.png /y icon4\com.android.contacts.png
copy 钱包\4.png /y icon4\com.huawei.wallet.png
copy 日历\4.png /y icon4\com.android.calendar.png
copy 荣耀阅读\4.png /y icon4\com.huawei.hnreader.png
copy 设置\4.png /y icon4\com.android.settings.png
copy 生活服务\4.png /y icon4\com.huawei.lives.png
copy 时钟\4.png /y icon4\com.android.deskclock.png
copy 手机管家\4.png /y icon4\com.huawei.systemmanager.png
copy 图库\4.png /y icon4\com.android.gallery3d.png
copy 相机\4.png /y icon4\com.huawei.camera.png
copy 音乐\4.png /y icon4\com.android.mediacenter.png
copy 应用市场\4.png /y icon4\com.huawei.appmarket.png
copy 邮件\4.png /y icon4\com.android.email.png
copy 浏览器\4.png /y icon4\com.android.browser.png
copy 浏览器2\4.png /y icon4\com.huawei.browser.png
copy 游戏中心1\4.png /y icon4\com.huawei.gamebox.globald.png
copy 游戏中心2\4.png /y icon4\com.huawei.gamebox.png
copy 游戏中心3\4.png /y icon4\com.huawei.gamecenter.png
copy 运动健康\4.png /y icon4\com.huawei.health.png
copy 主题\4.png /y icon4\com.huawei.android.thememanager.png

md icon5
copy 备忘录\5.png /y icon5\com.example.android.notepad.png
copy 电话\5.png /y icon5\com.android.contacts.activities.DialtactsActivity.png
copy 短信\5.png /y icon5\com.android.mms.png
copy 服务\5.png /y icon5\com.huawei.phoneservice.png
copy 华为阅读1\5.png /y icon5\com.huawei.hwireader.png
copy 华为阅读2\5.png /y icon5\com.huawei.hwread.al.png
copy 联系人\5.png /y icon5\com.android.contacts.png
copy 钱包\5.png /y icon5\com.huawei.wallet.png
copy 日历\5.png /y icon5\com.android.calendar.png
copy 荣耀阅读\5.png /y icon5\com.huawei.hnreader.png
copy 设置\5.png /y icon5\com.android.settings.png
copy 生活服务\5.png /y icon5\com.huawei.lives.png
copy 时钟\5.png /y icon5\com.android.deskclock.png
copy 手机管家\5.png /y icon5\com.huawei.systemmanager.png
copy 图库\5.png /y icon5\com.android.gallery3d.png
copy 相机\5.png /y icon5\com.huawei.camera.png
copy 音乐\5.png /y icon5\com.android.mediacenter.png
copy 应用市场\5.png /y icon5\com.huawei.appmarket.png
copy 邮件\5.png /y icon5\com.android.email.png
copy 浏览器\5.png /y icon5\com.android.browser.png
copy 浏览器2\5.png /y icon5\com.huawei.browser.png
copy 游戏中心1\5.png /y icon5\com.huawei.gamebox.globald.png
copy 游戏中心2\5.png /y icon5\com.huawei.gamebox.png
copy 游戏中心3\5.png /y icon5\com.huawei.gamecenter.png
copy 运动健康\5.png /y icon5\com.huawei.health.png
copy 主题\5.png /y icon5\com.huawei.android.thememanager.png

md icon6
copy 备忘录\6.png /y icon6\com.example.android.notepad.png
copy 电话\6.png /y icon6\com.android.contacts.activities.DialtactsActivity.png
copy 短信\6.png /y icon6\com.android.mms.png
copy 服务\6.png /y icon6\com.huawei.phoneservice.png
copy 华为阅读1\6.png /y icon6\com.huawei.hwireader.png
copy 华为阅读2\6.png /y icon6\com.huawei.hwread.al.png
copy 联系人\6.png /y icon6\com.android.contacts.png
copy 钱包\6.png /y icon6\com.huawei.wallet.png
copy 日历\6.png /y icon6\com.android.calendar.png
copy 荣耀阅读\6.png /y icon6\com.huawei.hnreader.png
copy 设置\6.png /y icon6\com.android.settings.png
copy 生活服务\6.png /y icon6\com.huawei.lives.png
copy 时钟\6.png /y icon6\com.android.deskclock.png
copy 手机管家\6.png /y icon6\com.huawei.systemmanager.png
copy 图库\6.png /y icon6\com.android.gallery3d.png
copy 相机\6.png /y icon6\com.huawei.camera.png
copy 音乐\6.png /y icon6\com.android.mediacenter.png
copy 应用市场\6.png /y icon6\com.huawei.appmarket.png
copy 邮件\6.png /y icon6\com.android.email.png
copy 浏览器\6.png /y icon6\com.android.browser.png
copy 浏览器2\6.png /y icon6\com.huawei.browser.png
copy 游戏中心1\6.png /y icon6\com.huawei.gamebox.globald.png
copy 游戏中心2\6.png /y icon6\com.huawei.gamebox.png
copy 游戏中心3\6.png /y icon6\com.huawei.gamecenter.png
copy 运动健康\6.png /y icon6\com.huawei.health.png
copy 主题\6.png /y icon6\com.huawei.android.thememanager.png

md icon7
copy 备忘录\7.png /y icon7\com.example.android.notepad.png
copy 电话\7.png /y icon7\com.android.contacts.activities.DialtactsActivity.png
copy 短信\7.png /y icon7\com.android.mms.png
copy 服务\7.png /y icon7\com.huawei.phoneservice.png
copy 华为阅读1\7.png /y icon7\com.huawei.hwireader.png
copy 华为阅读2\7.png /y icon7\com.huawei.hwread.al.png
copy 联系人\7.png /y icon7\com.android.contacts.png
copy 钱包\7.png /y icon7\com.huawei.wallet.png
copy 日历\7.png /y icon7\com.android.calendar.png
copy 荣耀阅读\7.png /y icon7\com.huawei.hnreader.png
copy 设置\7.png /y icon7\com.android.settings.png
copy 生活服务\7.png /y icon7\com.huawei.lives.png
copy 时钟\7.png /y icon7\com.android.deskclock.png
copy 手机管家\7.png /y icon7\com.huawei.systemmanager.png
copy 图库\7.png /y icon7\com.android.gallery3d.png
copy 相机\7.png /y icon7\com.huawei.camera.png
copy 音乐\7.png /y icon7\com.android.mediacenter.png
copy 应用市场\7.png /y icon7\com.huawei.appmarket.png
copy 邮件\7.png /y icon7\com.android.email.png
copy 浏览器\7.png /y icon7\com.android.browser.png
copy 浏览器2\7.png /y icon7\com.huawei.browser.png
copy 游戏中心1\7.png /y icon7\com.huawei.gamebox.globald.png
copy 游戏中心2\7.png /y icon7\com.huawei.gamebox.png
copy 游戏中心3\7.png /y icon7\com.huawei.gamecenter.png
copy 运动健康\7.png /y icon7\com.huawei.health.png
copy 主题\7.png /y icon7\com.huawei.android.thememanager.png

md icon8
copy 备忘录\8.png /y icon8\com.example.android.notepad.png
copy 电话\8.png /y icon8\com.android.contacts.activities.DialtactsActivity.png
copy 短信\8.png /y icon8\com.android.mms.png
copy 服务\8.png /y icon8\com.huawei.phoneservice.png
copy 华为阅读1\8.png /y icon8\com.huawei.hwireader.png
copy 华为阅读2\8.png /y icon8\com.huawei.hwread.al.png
copy 联系人\8.png /y icon8\com.android.contacts.png
copy 钱包\8.png /y icon8\com.huawei.wallet.png
copy 日历\8.png /y icon8\com.android.calendar.png
copy 荣耀阅读\8.png /y icon8\com.huawei.hnreader.png
copy 设置\8.png /y icon8\com.android.settings.png
copy 生活服务\8.png /y icon8\com.huawei.lives.png
copy 时钟\8.png /y icon8\com.android.deskclock.png
copy 手机管家\8.png /y icon8\com.huawei.systemmanager.png
copy 图库\8.png /y icon8\com.android.gallery3d.png
copy 相机\8.png /y icon8\com.huawei.camera.png
copy 音乐\8.png /y icon8\com.android.mediacenter.png
copy 应用市场\8.png /y icon8\com.huawei.appmarket.png
copy 邮件\8.png /y icon8\com.android.email.png
copy 浏览器\8.png /y icon8\com.android.browser.png
copy 浏览器2\8.png /y icon8\com.huawei.browser.png
copy 游戏中心1\8.png /y icon8\com.huawei.gamebox.globald.png
copy 游戏中心2\8.png /y icon8\com.huawei.gamebox.png
copy 游戏中心3\8.png /y icon8\com.huawei.gamecenter.png
copy 运动健康\8.png /y icon8\com.huawei.health.png
copy 主题\8.png /y icon8\com.huawei.android.thememanager.png
md icon9
copy 备忘录\9.png /y icon9\com.example.android.notepad.png
copy 电话\9.png /y icon9\com.android.contacts.activities.DialtactsActivity.png
copy 短信\9.png /y icon9\com.android.mms.png
copy 服务\9.png /y icon9\com.huawei.phoneservice.png
copy 华为阅读1\9.png /y icon9\com.huawei.hwireader.png
copy 华为阅读2\9.png /y icon9\com.huawei.hwread.al.png
copy 联系人\9.png /y icon9\com.android.contacts.png
copy 钱包\9.png /y icon9\com.huawei.wallet.png
copy 日历\9.png /y icon9\com.android.calendar.png
copy 荣耀阅读\9.png /y icon9\com.huawei.hnreader.png
copy 设置\9.png /y icon9\com.android.settings.png
copy 生活服务\9.png /y icon9\com.huawei.lives.png
copy 时钟\9.png /y icon9\com.android.deskclock.png
copy 手机管家\9.png /y icon9\com.huawei.systemmanager.png
copy 图库\9.png /y icon9\com.android.gallery3d.png
copy 相机\9.png /y icon9\com.huawei.camera.png
copy 音乐\9.png /y icon9\com.android.mediacenter.png
copy 应用市场\9.png /y icon9\com.huawei.appmarket.png
copy 邮件\9.png /y icon9\com.android.email.png
copy 浏览器\9.png /y icon9\com.android.browser.png
copy 浏览器2\9.png /y icon9\com.huawei.browser.png
copy 游戏中心1\9.png /y icon9\com.huawei.gamebox.globald.png
copy 游戏中心2\9.png /y icon9\com.huawei.gamebox.png
copy 游戏中心3\9.png /y icon9\com.huawei.gamecenter.png
copy 运动健康\9.png /y icon9\com.huawei.health.png
copy 主题\9.png /y icon9\com.huawei.android.thememanager.png

md icon10
copy 备忘录\10.png /y icon10\com.example.android.notepad.png
copy 电话\10.png /y icon10\com.android.contacts.activities.DialtactsActivity.png
copy 短信\10.png /y icon10\com.android.mms.png
copy 服务\10.png /y icon10\com.huawei.phoneservice.png
copy 华为阅读1\10.png /y icon10\com.huawei.hwireader.png
copy 华为阅读2\10.png /y icon10\com.huawei.hwread.al.png
copy 联系人\10.png /y icon10\com.android.contacts.png
copy 钱包\10.png /y icon10\com.huawei.wallet.png
copy 日历\10.png /y icon10\com.android.calendar.png
copy 荣耀阅读\10.png /y icon10\com.huawei.hnreader.png
copy 设置\10.png /y icon10\com.android.settings.png
copy 生活服务\10.png /y icon10\com.huawei.lives.png
copy 时钟\10.png /y icon10\com.android.deskclock.png
copy 手机管家\10.png /y icon10\com.huawei.systemmanager.png
copy 图库\10.png /y icon10\com.android.gallery3d.png
copy 相机\10.png /y icon10\com.huawei.camera.png
copy 音乐\10.png /y icon10\com.android.mediacenter.png
copy 应用市场\10.png /y icon10\com.huawei.appmarket.png
copy 邮件\10.png /y icon10\com.android.email.png
copy 浏览器\10.png /y icon10\com.android.browser.png
copy 浏览器2\10.png /y icon10\com.huawei.browser.png
copy 游戏中心1\10.png /y icon10\com.huawei.gamebox.globald.png
copy 游戏中心2\10.png /y icon10\com.huawei.gamebox.png
copy 游戏中心3\10.png /y icon10\com.huawei.gamecenter.png
copy 运动健康\10.png /y icon10\com.huawei.health.png
copy 主题\10.png /y icon10\com.huawei.android.thememanager.png

md icon11
copy 备忘录\11.png /y icon11\com.example.android.notepad.png
copy 电话\11.png /y icon11\com.android.contacts.activities.DialtactsActivity.png
copy 短信\11.png /y icon11\com.android.mms.png
copy 服务\11.png /y icon11\com.huawei.phoneservice.png
copy 华为阅读1\11.png /y icon11\com.huawei.hwireader.png
copy 华为阅读2\11.png /y icon11\com.huawei.hwread.al.png
copy 联系人\11.png /y icon11\com.android.contacts.png
copy 钱包\11.png /y icon11\com.huawei.wallet.png
copy 日历\11.png /y icon11\com.android.calendar.png
copy 荣耀阅读\11.png /y icon11\com.huawei.hnreader.png
copy 设置\11.png /y icon11\com.android.settings.png
copy 生活服务\11.png /y icon11\com.huawei.lives.png
copy 时钟\11.png /y icon11\com.android.deskclock.png
copy 手机管家\11.png /y icon11\com.huawei.systemmanager.png
copy 图库\11.png /y icon11\com.android.gallery3d.png
copy 相机\11.png /y icon11\com.huawei.camera.png
copy 音乐\11.png /y icon11\com.android.mediacenter.png
copy 应用市场\11.png /y icon11\com.huawei.appmarket.png
copy 邮件\11.png /y icon11\com.android.email.png
copy 浏览器\11.png /y icon11\com.android.browser.png
copy 浏览器2\11.png /y icon11\com.huawei.browser.png
copy 游戏中心1\11.png /y icon11\com.huawei.gamebox.globald.png
copy 游戏中心2\11.png /y icon11\com.huawei.gamebox.png
copy 游戏中心3\11.png /y icon11\com.huawei.gamecenter.png
copy 运动健康\11.png /y icon11\com.huawei.health.png
copy 主题\11.png /y icon11\com.huawei.android.thememanager.png

md icon12
copy 备忘录\12.png /y icon12\com.example.android.notepad.png
copy 电话\12.png /y icon12\com.android.contacts.activities.DialtactsActivity.png
copy 短信\12.png /y icon12\com.android.mms.png
copy 服务\12.png /y icon12\com.huawei.phoneservice.png
copy 华为阅读1\12.png /y icon12\com.huawei.hwireader.png
copy 华为阅读2\12.png /y icon12\com.huawei.hwread.al.png
copy 联系人\12.png /y icon12\com.android.contacts.png
copy 钱包\12.png /y icon12\com.huawei.wallet.png
copy 日历\12.png /y icon12\com.android.calendar.png
copy 荣耀阅读\12.png /y icon12\com.huawei.hnreader.png
copy 设置\12.png /y icon12\com.android.settings.png
copy 生活服务\12.png /y icon12\com.huawei.lives.png
copy 时钟\12.png /y icon12\com.android.deskclock.png
copy 手机管家\12.png /y icon12\com.huawei.systemmanager.png
copy 图库\12.png /y icon12\com.android.gallery3d.png
copy 相机\12.png /y icon12\com.huawei.camera.png
copy 音乐\12.png /y icon12\com.android.mediacenter.png
copy 应用市场\12.png /y icon12\com.huawei.appmarket.png
copy 邮件\12.png /y icon12\com.android.email.png
copy 浏览器\12.png /y icon12\com.android.browser.png
copy 浏览器2\12.png /y icon12\com.huawei.browser.png
copy 游戏中心1\12.png /y icon12\com.huawei.gamebox.globald.png
copy 游戏中心2\12.png /y icon12\com.huawei.gamebox.png
copy 游戏中心3\12.png /y icon12\com.huawei.gamecenter.png
copy 运动健康\12.png /y icon12\com.huawei.health.png
copy 主题\12.png /y icon12\com.huawei.android.thememanager.png

md icon13
copy 备忘录\13.png /y icon13\com.example.android.notepad.png
copy 电话\13.png /y icon13\com.android.contacts.activities.DialtactsActivity.png
copy 短信\13.png /y icon13\com.android.mms.png
copy 服务\13.png /y icon13\com.huawei.phoneservice.png
copy 华为阅读1\13.png /y icon13\com.huawei.hwireader.png
copy 华为阅读2\13.png /y icon13\com.huawei.hwread.al.png
copy 联系人\13.png /y icon13\com.android.contacts.png
copy 钱包\13.png /y icon13\com.huawei.wallet.png
copy 日历\13.png /y icon13\com.android.calendar.png
copy 荣耀阅读\13.png /y icon13\com.huawei.hnreader.png
copy 设置\13.png /y icon13\com.android.settings.png
copy 生活服务\13.png /y icon13\com.huawei.lives.png
copy 时钟\13.png /y icon13\com.android.deskclock.png
copy 手机管家\13.png /y icon13\com.huawei.systemmanager.png
copy 图库\13.png /y icon13\com.android.gallery3d.png
copy 相机\13.png /y icon13\com.huawei.camera.png
copy 音乐\13.png /y icon13\com.android.mediacenter.png
copy 应用市场\13.png /y icon13\com.huawei.appmarket.png
copy 邮件\13.png /y icon13\com.android.email.png
copy 浏览器\13.png /y icon13\com.android.browser.png
copy 浏览器2\13.png /y icon13\com.huawei.browser.png
copy 游戏中心1\13.png /y icon13\com.huawei.gamebox.globald.png
copy 游戏中心2\13.png /y icon13\com.huawei.gamebox.png
copy 游戏中心3\13.png /y icon13\com.huawei.gamecenter.png
copy 运动健康\13.png /y icon13\com.huawei.health.png
copy 主题\13.png /y icon13\com.huawei.android.thememanager.png
